from __future__ import annotations
import sympy as sp
import numpy as np

from typing import Callable, List, Sequence, Tuple, Union, Optional

from scipy.optimize import least_squares

import re
from pathlib import Path

from .constraints import Constraint, ConstraintSet

class Transformation:
    """
    Single-parameter SymPy transformation with bounds and sampling mode.
    """

    def __init__(
        self,
        kernel: Callable[[sp.Expr, Union[sp.Symbol, sp.Expr, float]], sp.Expr],
        param_bounds: Sequence[float],
        idx: int,
        name: Optional[str] = None,
        sample: str = 'uniform',    
    ):
        """Args:
            kernel (Callable): Maps (expr, eps) -> transformed expr.
            param_bounds (Sequence[float]): [low, high] bounds for eps.
            idx (int): Identifier index for 'T{idx}'.
            name (Optional[str]): Human-readable name.
            sample (str): Sampling mode ('uniform' or 'log').
        """
        assert len(param_bounds) == 2, "param_bounds must be [low, high]"
        self.kernel = kernel
        self.param_bounds = (float(param_bounds[0]), float(param_bounds[1]))
        self.idx = idx
        self.name = name or getattr(kernel, "__name__", "transformation")
        self.sample = sample

    def __call__(self, expr: sp.Expr, param: Union[str, float, sp.Expr]) -> sp.Expr:
        if isinstance(param, str):
            eps = sp.Symbol(param, real=True)
        else:
            eps = param
        return self.kernel(expr, eps)

    def __repr__(self):
        return f"<Transformation {self.idx}: {self.kernel.__name__}>"

    def index(self):
        return self.kernel.__name__.replace('_', '')
    
    
class BrickFamily:
    """Brick family: parametric solution generated by applying transformations to a seed solution.
    """
    def __init__(self,
                 seed_solution: sp.Expr,
                 trafos: List[Transformation],
                 coords_sym: List[sp.Symbol]
                 ):
        """Args:
            seed_solution (sp.Expr): Seed expression.
            trafos (List[Transformation]): Transformations to apply (inner -> outer).
            coords_sym (List[sp.Symbol]): Coordinate symbols order.
        """
        self.seed_solution = seed_solution
        self.trafos = trafos if isinstance(trafos, list) else [trafos]
        self.coords_sym = coords_sym
        self.params_sym = []
        self.params_bounds = []
        self.param_sample = []
        self.apply_transform()

    def __repr__(self):
        trafos_repr = ''
        for trafo in self.trafos:
            trafos_repr = f'T{trafo.idx}•' + trafos_repr
        return f"{trafos_repr[:-1]}( {self.seed_solution} )"

    def apply_transform(self):
        """Build transformed expression, collect parameters, and compile f_np.
        Also compile analytical Jacobian (partial derivatives w.r.t. each parameter).
        """
        self.expression = self.seed_solution
        for i in range(len(self.trafos)):
            trafo = self.trafos[i]
            param_name = f'θ{trafo.idx}_{i}'
            param_sym = sp.Symbol(param_name, real=True)
            self.params_sym.append(param_sym)
            self.params_bounds.append(trafo.param_bounds)
            self.param_sample.append(trafo.sample)
            self.expression = trafo(self.expression, param_sym)

        self._f = sp.lambdify(self.coords_sym + self.params_sym, self.expression, modules="numpy")
        
        # Compile analytical Jacobian: ∂φ/∂θ_i for each parameter
        self._df_dtheta = []
        for param_sym in self.params_sym:
            deriv_expr = sp.diff(self.expression, param_sym)
            deriv_fn = sp.lambdify(self.coords_sym + self.params_sym, deriv_expr, modules="numpy")
            self._df_dtheta.append(deriv_fn)
        
        # Cache for coordinate derivative lambdas: {deriv_order: lambda}
        self._df_dcoord: dict = {}

    def _get_deriv_func(self, deriv_order: Tuple[int, ...]):
        """Get or compile lambda for coordinate derivative.
        
        Args:
            deriv_order: Derivative order per coordinate, e.g., (0, 1) for ∂/∂t.
        
        Returns:
            Callable: Lambda function (coords..., params...) -> values.
        """
        if deriv_order in self._df_dcoord:
            return self._df_dcoord[deriv_order]
        
        # Build derivative expression
        expr = self.expression
        for coord_idx, order in enumerate(deriv_order):
            if order > 0:
                expr = sp.diff(expr, self.coords_sym[coord_idx], order)
        
        # Compile and cache
        func = sp.lambdify(self.coords_sym + self.params_sym, expr, modules="numpy")
        self._df_dcoord[deriv_order] = func
        return func

    def eval(self, X: np.ndarray, params: np.ndarray, deriv_order: Optional[Tuple[int, ...]] = None) -> np.ndarray:
        """Evaluate brick family function or its coordinate derivative at points.
        
        Args:
            X: Input points, shape (n_samples, n_coords).
            params: Parameter vector, shape (n_params,).
            deriv_order: Derivative order per coordinate, e.g., (0, 1) for ∂/∂t.
                None or (0, 0, ...) returns the function value.
        
        Returns:
            np.ndarray: Values at X, shape (n_samples,).
        """
        if deriv_order is None or all(d == 0 for d in deriv_order):
            return self._f(*X.T, *params)
        func = self._get_deriv_func(deriv_order)
        return func(*X.T, *params)

    def eval_jacobian(self, X: np.ndarray, params: np.ndarray) -> np.ndarray:
        """Evaluate analytical Jacobian ∂φ/∂θ at given points and parameters.
        
        Args:
            X (np.ndarray): Input points, shape (n_samples, n_coords)
            params (np.ndarray): Parameter vector, shape (n_params,)
        
        Returns:
            np.ndarray: Jacobian matrix, shape (n_samples, n_params)
        """
        n_samples = X.shape[0]
        n_params = len(self.params_sym)
        jac = np.zeros((n_samples, n_params))
        
        for i, deriv_fn in enumerate(self._df_dtheta):
            jac[:, i] = deriv_fn(*X.T, *params)
        
        return jac

    @classmethod
    def init_from_str(cls,
                      brick_str: str,
                      trafo_catalog: List[Transformation],
                      coords_sym: List[sp.Symbol],
                      ) -> BrickFamily:
        """
        Parse a brick family string into a BrickFamily object.
        Args:
            brick_str (str): Definition like 'T4(0,1000,log) T1 sin(x) exp(-t)'.
            trafo_catalog (List[Transformation]): Available transformations.
            coords_sym (List[sp.Symbol]): Coordinate symbols.
        Returns:
            BrickFamily: Parsed brick family instance.
        """
        matches = list(re.finditer(r"\bT(\d+)(?:\(([^)]*)\))?", brick_str))
        trafos_tokens = [(int(m.group(1)), m.group(2)) for m in matches]
        expr_str = brick_str[matches[-1].end():].strip() if matches else brick_str.strip()

        expr = sp.parse_expr(expr_str, transformations="all", local_dict={s.name: s for s in coords_sym})
        
        catalog_idx = [trafo.idx for trafo in trafo_catalog]
        assert len(catalog_idx) == len(set(catalog_idx)), "idx attributes of default trafos must be unique"
        trafos: List[Transformation] = []
        for idx, override in reversed(trafos_tokens):
            if idx not in catalog_idx:
                raise KeyError(f"Unknown transformation index T{idx}")
            trafo = trafo_catalog[catalog_idx.index(idx)]
            if not override:
                trafos.append(trafo)
            else:
                parts = override.split(',')
                bounds = [float(p) for p in parts[:2]]
                sample = parts[2].strip() if len(parts) == 3 else 'uniform'
                trafo_updated = Transformation(kernel=trafo.kernel,
                                               idx=trafo.idx,
                                               name=trafo.name,
                                               param_bounds=bounds,
                                               sample=sample)
                trafos.append(trafo_updated)

        return cls(seed_solution=expr, trafos=trafos, coords_sym=coords_sym)

    def to_string(self) -> str:
        """
        Serialize BrickFamily into a config string:
        e.g., 'T4(0, 1000, log) T1(0, 3.14, uniform) sin(x) exp(-t)'
        """
        t_parts = []
        for trafo in reversed(self.trafos):  # outermost -> innermost
            low, high = trafo.param_bounds
            t_parts.append(f"T{trafo.idx}({low:.15g}, {high:.15g}, {trafo.sample})")

        expr_str = sp.sstr(self.seed_solution)
        return " ".join(t_parts + [expr_str])

    def sample_params(self, pool_size: int, sampler: str = 'random', sobol_seed=0) -> np.ndarray:
        """Sample parameter vectors within bounds.
        Args:
            pool_size (int): Number of samples.
            sampler (str): 'random' or 'sobol'.
            sobol_seed (int): Seed for Sobol sampling.
        Returns:
            np.ndarray: Samples of shape (pool_size, n_params).
        """
        n_params = len(self.params_bounds)
        if n_params == 0:
            return np.empty((pool_size, 0))

        if sampler == 'sobol':
            from scipy.stats import qmc
            engine = qmc.Sobol(d=n_params, scramble=True, seed=sobol_seed)
            # Use power-of-two fast path when possible
            if pool_size > 0 and (pool_size & (pool_size - 1)) == 0:
                U = engine.random_base2(m=int(np.log2(pool_size)))
            else:
                U = engine.random(pool_size)
        else:
            U = np.random.uniform(0.0, 1.0, size=(pool_size, n_params))

        sample = []
        for i, (low, high) in enumerate(self.params_bounds):
            if self.param_sample[i] == 'uniform':
                param_pool = low + (high - low) * U[:, i]
            elif self.param_sample[i] == 'log':
                param_pool = low * (high / low) ** U[:, i]
            else:
                raise ValueError(f"Unknown sampling type: {self.param_sample[i]}")
            sample.append(param_pool)

        return np.column_stack(sample)


class Brick:
    """
    A concrete brick: specific instantiation of a brick family with parameter values.
    """
    def __init__(self, family: BrickFamily, params, family_idx: int = None):
        self.family = family
        self.params: np.ndarray = params
        self.family_idx = family_idx

    def __repr__(self):
        params_names = [sym.name.split('_')[0] for sym in self.family.params_sym]
        params_str = ' '.join([f'{params_names[i]}:{self.params[i]:.1e}' for i in range(len(params_names))])
        return f"{params_str}"


class LieSolver:
    """Linear model over bricks (instantiated brick families) fitted by LS with NLLS refinement.
    """    
    def __init__(
            self,
            families: List[BrickFamily],
            constraints: ConstraintSet,
            ridge: float = 0.0,
            sobol_seed: int = 0,
        ):
        """Initialize LieSolver.
        
        Args:
            families: List of BrickFamily objects defining the function space.
            constraints: ConstraintSet with IC/BC/derivative constraints.
            ridge: Ridge regularization coefficient.
            sobol_seed: Seed for Sobol sampling of parameters.
        """
        self.families = families
        self.constraints = constraints
        self.ridge = ridge
        self.sobol_seed = sobol_seed

        self.bricks: List[Brick] = []
        self.amplitudes = np.array([])
        self.mse = np.inf

    def __call__(self, X: np.ndarray):
        F = self.feature_matrix(self.bricks, X)
        return F @ self.amplitudes

    def save(self, folder: Path = None, filename = None) -> None:
        """Save model arrays and metadata to NPZ."""
        if filename is None:
            filename = f'model_Nfamilies{len(self.families)}_Nbricks{len(self.bricks)}_mse{self.mse:.0e}.npz'
        if folder is None:
            folder = Path.cwd()
        path = Path(folder) / filename
        
        # Save constraint data
        n_constraints = len(self.constraints.constraints)
        constraint_x = [c.x for c in self.constraints.constraints]
        constraint_y = [c.y for c in self.constraints.constraints]
        constraint_deriv_order = [c.deriv_order for c in self.constraints.constraints]
        constraint_weight = [c.weight for c in self.constraints.constraints]
        constraint_name = [c.name for c in self.constraints.constraints]
        
        save_dict = {
            'families_str': [family.to_string() for family in self.families],
            'family_idx': [brick.family_idx for brick in self.bricks],
            'theta': np.array([brick.params for brick in self.bricks], dtype=object),
            'ridge': self.ridge,
            'sobol_seed': self.sobol_seed,
            'a': self.amplitudes,
            'mse': self.mse,
            # Constraint data
            'n_constraints': n_constraints,
            'constraint_x': np.array(constraint_x, dtype=object),
            'constraint_y': np.array(constraint_y, dtype=object),
            'constraint_deriv_order': np.array(constraint_deriv_order, dtype=object),
            'constraint_weight': np.array(constraint_weight),
            'constraint_name': np.array(constraint_name, dtype=object),
        }
        
        np.savez_compressed(path, **save_dict)

    @classmethod
    def init_from_npz(cls, file, trafos, coords_sym):
        
        data = np.load(file, allow_pickle=True)
        
        # Rebuild constraints from saved data
        n_constraints = int(data['n_constraints'])
        constraint_x = data['constraint_x']
        constraint_y = data['constraint_y']
        constraint_deriv_order = data['constraint_deriv_order']
        constraint_weight = data['constraint_weight']
        constraint_name = data['constraint_name']
        
        constraints = ConstraintSet()
        for i in range(n_constraints):
            constraints.add(Constraint(
                x=np.asarray(constraint_x[i]),
                y=np.asarray(constraint_y[i]),
                deriv_order=tuple(constraint_deriv_order[i]),
                weight=float(constraint_weight[i]),
                name=str(constraint_name[i]),
            ))
        
        model = cls(
            families=[BrickFamily.init_from_str(brick_str, trafos, coords_sym) for brick_str in data["families_str"]],
            constraints=constraints,
            ridge=float(np.asarray(data["ridge"]).item()),
            sobol_seed=int(np.asarray(data["sobol_seed"]).item()),
        )
        family_idx = data["family_idx"]
        theta = data["theta"]
        for i, fam_idx in enumerate(family_idx):
            model.add_defined_brick(int(fam_idx), np.asarray(theta[i]))
        
        # Rebuild amplitudes and MSE
        F = model.stacked_feature_matrix(model.bricks)
        Y = model.stacked_targets()
        model.amplitudes = model.ls_amplitudes(F, Y)
        r = F @ model.amplitudes - Y
        model.mse = float(np.mean(r ** 2))
        
        # Load history if available
        if "history_amplitudes" in data:
            model.history['amplitudes'] = list(data["history_amplitudes"])
            model.history['term_params'] = [list(tp) for tp in data["history_term_params"]]
            model.history['mse'] = list(data["history_mse"])
            model.history['n_terms'] = list(data["history_n_terms"])
            model.history['step_type'] = list(data["history_step_type"])
        
        data.close()
        return model

    def add_defined_brick(self, family_idx, params):
        brick = Brick(self.families[family_idx],
                      params=params,
                      family_idx=family_idx)
        self.bricks.append(brick)
    
    def remove_brick(self, brick_idx: int = -1):
        if not self.bricks:
            return None

        if brick_idx < 0:
            brick_idx += len(self.bricks)
        if brick_idx < 0 or brick_idx >= len(self.bricks):
            raise IndexError("brick_idx out of range")

        removed = self.bricks.pop(brick_idx)

        if self.bricks:
            F = self.stacked_feature_matrix(self.bricks)
            Y = self.stacked_targets()
            self.amplitudes = self.ls_amplitudes(F, Y)
            r = F @ self.amplitudes - Y
            self.mse = float(np.mean(r ** 2))
        else:
            self.amplitudes = np.zeros(0)
            Y = self.stacked_targets()
            self.mse = float(np.mean(Y ** 2))
        
        return removed

    def feature_matrix(self, bricks: List[Brick], X: np.ndarray) -> np.ndarray:
        """Build feature matrix for given bricks at points X."""
        cols = [brick.family.eval(X, brick.params) for brick in bricks]
        return np.stack(cols, axis=1)  # (L, M)
    
    def feature_matrix_derivative(
        self, 
        bricks: List[Brick], 
        X: np.ndarray, 
        deriv_order: Tuple[int, ...]
    ) -> np.ndarray:
        """Build feature matrix for derivative constraint.
        
        Args:
            bricks: List of Brick objects.
            X: Sample points, shape (N, dim).
            deriv_order: Derivative order per coordinate.
        
        Returns:
            np.ndarray: Feature matrix, shape (N, M).
        """
        if all(d == 0 for d in deriv_order):
            return self.feature_matrix(bricks, X)
        cols = [brick.family.eval(X, brick.params, deriv_order) for brick in bricks]
        return np.stack(cols, axis=1)
    
    def stacked_feature_matrix(self, bricks: List[Brick]) -> np.ndarray:
        """Build stacked feature matrix for all constraints.
        
        Each constraint block is scaled by sqrt(weight).
        
        Returns:
            np.ndarray: Stacked feature matrix, shape (total_samples, M).
        """
        if self.constraints is None or len(self.constraints) == 0:
            return self.feature_matrix(bricks)
        
        blocks = []
        for c in self.constraints:
            F_c = self.feature_matrix_derivative(bricks, c.x, c.deriv_order)
            blocks.append(np.sqrt(c.weight) * F_c)
        return np.vstack(blocks)
    
    def stacked_targets(self) -> np.ndarray:
        """Get stacked weighted target vector for all constraints."""
        return self.constraints.get_stacked_targets()

    def ls_amplitudes(self, F: np.ndarray, Y: np.ndarray) -> np.ndarray:
        """
        Solve least squares for amplitudes.
        Args:
            F (np.ndarray): Design matrix (L, M).
            Y (np.ndarray): Targets.
        Returns:
            np.ndarray: Amplitude vector (M,).
        """
        if F.shape[1] == 0:
            return np.zeros(0)
        if self.ridge > 0.0:
            FtF = F.T @ F
            FtY = F.T @ Y
            M = FtF.shape[0]
            a = np.linalg.solve(FtF + self.ridge * np.eye(M), FtY)
        else:
            a, *_ = np.linalg.lstsq(F, Y, rcond=None)
        return a

    def add_best_brick(self, pool_size: int = 1000):
        """Greedily add highest-scoring brick against residual.
        
        Args:
            pool_size (int): Number of parameter samples per brick family.
        Returns:
            float: Best cosine score.
        """
        # Compute current residual
        if len(self.bricks) == 0:
            r = self.stacked_targets()
        else:
            F = self.stacked_feature_matrix(self.bricks)
            Y_stacked = self.stacked_targets()
            a = self.ls_amplitudes(F, Y_stacked)
            r = Y_stacked - F @ a
        
        norm_r = np.linalg.norm(r) + 1e-12
        best_score = -np.inf
        best_brick = None

        for family_idx, family in enumerate(self.families):
            params_pool = family.sample_params(pool_size, self.sobol_seed)
            for p in params_pool:
                # Evaluate candidate brick across all constraints
                phi_parts = []
                for c in self.constraints:
                    phi_c = family.eval(c.x, p, c.deriv_order)
                    phi_parts.append(np.sqrt(c.weight) * phi_c)
                phi = np.concatenate(phi_parts)
                
                norm_phi = np.linalg.norm(phi) + 1e-12
                score = abs(np.dot(r, phi) / norm_phi / norm_r)
                if score > best_score:
                    best_score = score
                    best_brick = Brick(family, p.copy(), family_idx)
        
        const_score = abs(np.dot(r, np.ones_like(r)) / np.linalg.norm(np.ones_like(r)) / norm_r)
        if best_score < const_score:
            print(f'Add log: best score {best_score:.2e} is lower than constant score {const_score:.2e}')
        self.bricks.append(best_brick)
        
        # Recompute amplitudes and MSE
        F = self.stacked_feature_matrix(self.bricks)
        Y_stacked = self.stacked_targets()
        
        self.amplitudes = self.ls_amplitudes(F, Y_stacked)
        r = F @ self.amplitudes - Y_stacked
        mse = float(np.mean(r ** 2))
        if mse > self.mse:
            print('Add log: MSE worsened')
        self.mse = mse
        return best_score
        

    def _pack_theta(self, bricks: List[Brick]) -> np.ndarray:
        """Concatenate per-brick parameter vectors."""
        if not bricks:
            return np.zeros(0)
        return np.concatenate([brick.params for brick in bricks], axis=0)

    def _unpack_theta(self, theta: np.ndarray, bricks: List[Brick], active_idx) -> None:
        """
        Distribute a flat parameter vector theta across bricks with variable-length params.
        Expects each Brick.params to be a 1D array (size = number of params for that brick family).
        """
        idx = 0
        for i, brick in enumerate(bricks):
            if i in active_idx or not active_idx:
                n = int(np.size(brick.params))
                brick.params = np.asarray(theta[idx: idx + n]).copy()
                idx += n
        assert idx == theta.size, f"theta length {theta.size} != total params consumed {idx}"

    def _bounds_vector(self, bricks: List[Brick]) -> Tuple[np.ndarray, np.ndarray]:
        """Build lower/upper bounds vectors from brick family bounds."""
        lbs, ubs = [], []
        for brick in bricks:
            for bounds in brick.family.params_bounds:
                lb, ub = bounds
                lbs.append(lb)
                ubs.append(ub)
        if not lbs:
            return np.zeros(0), np.zeros(0)
        return np.array(lbs), np.array(ubs)

    def _residual_varpro(self, theta: np.ndarray, active_idx: List[int]) -> np.ndarray:
        """Compute residual using variable-projection with given theta.
        
        Caches amplitudes for use by _jacobian_varpro.
        """
        bricks = [Brick(brick.family, brick.params.copy()) for brick in self.bricks]
        self._unpack_theta(theta, bricks, active_idx)
        
        F = self._stacked_feature_matrix_for_bricks(bricks)
        Y = self.stacked_targets()
        
        a = self.ls_amplitudes(F, Y)
        self._cached_F = F
        self._cached_a = a
        self._cached_bricks = bricks
        self._cached_Y = Y
        return F @ a - Y
    
    def _stacked_feature_matrix_for_bricks(self, bricks: List[Brick]) -> np.ndarray:
        """Build stacked feature matrix for given bricks (not self.bricks)."""
        blocks = []
        for c in self.constraints:
            F_c = self.feature_matrix_derivative(bricks, c.x, c.deriv_order)
            blocks.append(np.sqrt(c.weight) * F_c)
        return np.vstack(blocks)
    
    def _jacobian_varpro(self, theta: np.ndarray, active_idx: List[int]) -> np.ndarray:
        """Analytical Jacobian of variable-projection residual: ∂r/∂θ.
        
        Requires _residual_varpro to have been called first (caches F, a).
        
        Formula: ∂r/∂θ = ∂F/∂θ · a + F · ∂a/∂θ
        Uses analytical ∂F/∂θ (from symbolic diff) and numerical ∂a/∂θ (via FD).
        
        Args:
            theta: Parameter vector (same as in _residual_varpro).
            active_idx: Indices of active bricks being optimized.
        
        Returns:
            np.ndarray: Jacobian matrix, shape (L, K).
        """
        F = self._cached_F
        a = self._cached_a
        bricks = self._cached_bricks
        Y = self._cached_Y
        L = F.shape[0]
        
        # Determine active indices
        if not active_idx:
            active_idx = list(range(len(bricks)))
        
        # Compute ∂F/∂θ analytically: (L, Ka) where Ka = number of active params
        # Build Jacobian for each constraint block
        dF_dtheta_list = []
        param_idx_to_brick_idx = {}
        param_offset = 0
        
        for brick_idx in active_idx:
            brick = bricks[brick_idx]
            jac_blocks = []
            for c in self.constraints:
                # TODO: implement eval_jacobian with deriv_order for full analytical Jacobian
                # For now, use numerical differentiation for derivative constraints
                jac_c = brick.family.eval_jacobian(c.x, brick.params)
                jac_blocks.append(np.sqrt(c.weight) * jac_c)
            jac_brick = np.vstack(jac_blocks)
            dF_dtheta_list.append(jac_brick)
            K_brick = jac_brick.shape[1]
            for local_j in range(K_brick):
                param_idx_to_brick_idx[param_offset + local_j] = brick_idx
            param_offset += K_brick
        
        dF_dtheta = np.hstack(dF_dtheta_list) if dF_dtheta_list else np.zeros((L, 0))
        Ka = dF_dtheta.shape[1]
        
        # First term: ∂F/∂θ · a
        jr_part1 = np.zeros((L, Ka))
        for j in range(Ka):
            brick_idx = param_idx_to_brick_idx[j]
            jr_part1[:, j] = dF_dtheta[:, j] * a[brick_idx]
        
        # Second term: F · ∂a/∂θ (numerical)
        jr_part2 = np.zeros((L, Ka))
        eps = 1e-8
        
        for j in range(Ka):
            theta_pert = theta.copy()
            theta_pert[j] += eps
            
            bricks_pert = [Brick(brick.family, brick.params.copy()) for brick in self.bricks]
            self._unpack_theta(theta_pert, bricks_pert, active_idx)
            
            F_pert = self._stacked_feature_matrix_for_bricks(bricks_pert)
            a_pert = self.ls_amplitudes(F_pert, Y)
            
            da_j = (a_pert - a) / eps
            jr_part2[:, j] = F @ da_j
        
        jac = jr_part1 + jr_part2
        return jac
    
    def refine(self, max_nfev: int = 10, active_idx: List[int] = []):
        """Nonlinear refinement of brick parameters via scipy.optimize.least_squares."""
        if active_idx:
            active_bricks = [self.bricks[i] for i in active_idx]
        else:
            active_bricks = self.bricks

        res = least_squares(
            fun=lambda th: self._residual_varpro(th, active_idx),
            jac=lambda th: self._jacobian_varpro(th, active_idx),
            x0=self._pack_theta(active_bricks),
            bounds=self._bounds_vector(active_bricks),
            method="trf",
            max_nfev=max_nfev,
            ftol=1e-12,
            xtol=1e-12,
            gtol=1e-12,
            verbose=0,
        )
        self._unpack_theta(res.x, self.bricks, active_idx)
        
        # Recompute amplitudes and MSE
        F = self.stacked_feature_matrix(self.bricks)
        Y = self.stacked_targets()
        
        self.amplitudes = self.ls_amplitudes(F, Y)
        r = F @ self.amplitudes - Y
        mse = float(np.mean(r ** 2))
        if mse > self.mse:
            print('Refine log: MSE worsened')
        elif mse == self.mse:
            print('Refine log: MSE stalled')
        self.mse = mse





