pde: heat_1d
experiment_name: heat-g5_4-mse4
seed: 0

data: 
  res: 100
  num_ic: 1000
  num_bc: 2000
  num_domain: 10_000
  range_dim:
    x: [0, 1]
    t: [0, 0.1]
  refresh: 1
  # New constraints format
  constraints:
    - expr: 0.5 * (tanh(500 * (x - 0.4)) - tanh(500 * (x - 0.6)))
    # - expr: sinc(10 * 2*pi*(x-0.3))
      loc: [t, 0]  # t = t_min (initial condition)
      deriv_order: [0, 0]
      weight: 1.0
      num_samples: 1000
      name: IC_u0
    - expr: 0  # Dirichlet BC at x=0
      loc: [x, 0]
      num_samples: 1000
      name: BC_left
    - expr: 0  # Dirichlet BC at x=1
      loc: [x, 1]
      num_samples: 1000
      name: BC_right

base: 
  - T4 T1(0,3.14) sin(x) exp(-t)
  - T1(0,1) T6(0.1,1e6,log) 1
  - T1(0,1) T6(0.1,1e6,log) T4 T1(0,3.14) sin(x) exp(-t)

fit:
  mse_tol: 9e-5
  max_terms: 60
  nfev_global: 4
  nfev_batch: 4 
  batch_size: 5000
  global_every: 5
  pool_size: 1000
