pde: heat_1d
experiment_name: heat-g20_10-b5_4-t60-base_edit5
seed: 0

data: 
  icbc_name: step
  # icbc_expr: sin(2*pi*x)
  res: 600  
  num_ic: 1000
  num_bc: 2000
  num_domain: 10_000
  range_dim:
  - [0, 1]
  - [0, 0.1] 
  refresh: 0

base: 
  - T4 T1(0,3.14) sin(x) exp(-t)
  - T1(0,1) T6(0.1,1000,log) 1
  - T1(0,1) T6(0.1,1000,log) T4 T1(0,3.14) sin(x) exp(-t)
  # - T1 T2 T4 x
  # - T1 T2 T4 x^2 + 2t
  # - T1 T2 T4 x^3 + 6tx
  # - T1 T2 T4 x^4 + 12t x^2 + 12 t^2

fit:
  mse_tol: 9e-7
  max_terms: 60   # 40->40s, 50->60s, 60->100+s, 70->200+s, 80->300+s
  nfev_global: 10  # 2-10 optimal
  nfev_batch: 4 
  batch_size: 5 # high value turns batch refine off
  global_every: 20 # 3-10 optimal
  pool_size: 1000
