experiment_name: torch_model
float_dtype: float32
device: cpu
seed: 0

pde: heat_equation_1d
n_terms: 20
n_expensive: 1

data: 
  ic_bcs_name: dirichlet_step
  N_fourier_modes: 700
  # parameters:
  #   u0: 1.0
  #   x0: 0.5
  #   sigma: 0.1
  #   diffusivity: 0.01
  #   sharpness: 200
  #   step_ratio: 0.2 # step from 0.4 to 0.6 of the domain 
  num_boundary: 1_000
  num_initial: 1_000
  num_test: 1_000
  num_domain: 10_000
  range_time: [0, 0.1]
  # range_spatial: [[0, 1], [0, 2]]
  range_spatial: [0, 1]
  # force_refresh: 1

training:
  - iterations: 100
    lr: 1.0e-1
    optimizer: adam
    log_interval: 20

  - iterations: 10
    optimizer: lbfgs
    log_interval: 1


